name: Release

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - run: echo ${{ github.event.workflow_run.head_branch }}

      # - name: Extract Version
      #   id: version
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: echo VERSION="${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"
      #
      # - name: Create Release
      #   id: create_release
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     name: FreeBSD ${{ steps.version.outputs.VERSION }}
      #     draft: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #
